Import('pluginenv', 'build_plugin')

localenv = pluginenv.Clone()
localenv.Append(LIBS=['faustwithllvm', 'zzub'])
localenv.Append(CPPPATH=["${LANTERNFISH_SRC_PATH}"])
localenv.Append(LIBS=['lanternfish'])

build_plugin(localenv, "faust_oscillator", ['faust_oscillator.cpp', 'faust_oscillator_info.cpp', 'faust_ui.cpp'])
