# encoding=utf8

# libzzub, Buzé, Aldrin
# Modular Sequencer
# Copyright (C) 2006 The Aldrin Development Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.


# lv2 plugin adapter by github.com/mitnuh
# based on the dssi adapter by
#     Copyright (C) 2006 Leonard Ritter (contact@leonard-ritter.com)
#     Copyright (C) 2008 James McDermott (jamesmichaelmcdermott@gmail.com)

Import('pluginenv', 'build_plugin')

lv2_pluginenv = pluginenv.Clone()
lv2_pluginenv.Append(LIBS=['lilv-0', 'suil-0', 'gtk-3'])

#lv2_pluginenv.Append(CCFLAGS=[ '-DUSE_LILV', '-DUSE_LV2' ])

lv2_pluginenv.Append(CCFLAGS='-pthread `pkg-config gtk+-3.0 suil-0 lilv-0 --cflags` -Ilibneil/src/libzzub -Ilibneil/src/plugins/lv2adapter')

if lv2_pluginenv['LV2'] == True:
    lv2_files = [ 'lv2_adapter.cpp', 
        'lv2_adapter_ui.cpp', 
        'Ports.cpp', 
        'lv2_zzub_info.cpp', 
        'PluginWorld.cpp', 
        'lv2_utils.cpp', 
        # 'lv2_defines.cpp',  
        'ext/lv2_evbuf.c', 'ext/symap.c', 'zix/ring.c', 'features/worker.cpp'
    ]
    
    lv2_build = build_plugin(lv2_pluginenv, 'lv2adapter', lv2_files)
