Import('pluginenv', 'build_plugin')

vst_pluginenv = pluginenv.Clone()
vst_pluginenv.Append(LIBS=['boost_system', 'boost_filesystem'])

vst_pluginenv.Append(CCFLAGS='-pthread `pkg-config gtk+-3.0 --cflags` -Ilibneil/src/libzzub -Ilibneil/src/plugins/vst3adapter/ -Ilibneil/src/plugins/vst3adapter/pluginterfaces -Ilibneil/src/plugins/vst3adapter/public.sdk -Ilibneil/src/plugins/vst3adapter/base -Ilibneil/src/plugins/vst3adapter/vst4gui/vstgui')

vst_build = build_plugin(vst_pluginenv, 'vst3adapter', [ ])
