#Import('env', 'posix', 'install_lib')

#import glob

#localenv = env.Clone()
#localenv.Append(CPPFLAGS=['-O3'])

#files = [""]

#neil_utils_static = localenv.StaticLibrary('${LIB_BUILD_PATH}/utils', files)

#Export('neil_utils_static')
