# Neil
# Modular Sequencer
# Copyright (C) 2006 The Neil Development Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

Import('install')
import glob
import os.path

for filename in glob.glob('packages/*.neil-component'):
    install('${SHARE_PATH}/components/packages', filename)

for filename in glob.glob('*.py'):
    install('${SHARE_PATH}/components', filename)

for (modulename, _) in [os.path.split(filename) for filename in glob.glob('**/__init__.py', recursive=True)]:
    for (dirname, filename) in [os.path.split(filename) for filename in glob.glob(f'{modulename}/*.py')]:
        install('${SHARE_PATH}/components/' + dirname, dirname + '/' + filename)

    for (dirname, filename) in [os.path.split(filename) for filename in glob.glob(f'{modulename}/*.json')]:
        install('${SHARE_PATH}/components/' + dirname, dirname + '/' + filename)